#pragma once

#include <vector>
#include <set>
#include <algorithm>
#include <iostream>
#include <fmt/ranges.h>


class Password {
    std::string name;
    std::string password;
    std::string category;
    std::string login;
    std::string website;
public:

    /**
     * \brief constructor of Password object.
     * Creates an object of type class.
     *
     * @param name will be a name
     */
    Password(std::string name);

    /**
     * \brief gets a name.
     *
     * @return name
     *
    */
    std::string getName();

    /**
     * \brief creates a password.
     * Function creates a password in two ways: user's own and generated by the program.
     *
    */
    static void create();

    /**
     * \brief generates a password.
     * Function generates a password, asking a user about filters for generation.
     *
     * @return generated password
     *
    */
    static std::string generate();

    /**
     * \brief sets a password.
     * Sets a password manually.
     *
     * @param password
     *
    */
    void setPassword(std::string password);
};